kafka:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 3Gi
      cpu: 2000m
  # For all internal listeners
  listeners:
    networkPolicyPeers:
      - namespaceSelector:
        matchingLabels:
          project: abc
      - namespaceSelector:
        matchingLabels:
          project: xyz
  
  ownCerts:
    enabled: false
  networkPolicy:
    enabled: false
  customBootstrap:
    enabled: false
    host: test.ch
  jvmOptions:
    enabled: false
  rackawarness:
    enabled: false

  storage:
    volumes:
    - id: 0
      type: persistent-claim 
      size: 15G1 
      deleteClaim: true
    - id: 1 
      type: persistent-claim 
      size: 15Gi 
      deleteClaim: true
    - id: 2
      type: persistent-claim
      size: 15Gi 
      deleteClaim: true


zookeeper:
  replicas: 3
  resources:
    requests:
      cpu: 300m
      memory: 500mi
    limits:
      memory: 2Gi
      cpu: 1500m
  storage:
    class: test

entityOperator:
  topicOperator:
    resources:
      requests:
        cpu: 300m
        memory: 500mi
      limits:
        memory: 2Gi
        cpu: 1500m

  userOperator:
    resources:
      requests:
        cpu: 300m
        memory: 500mi
      limits:
        memory: 2Gi
        cpu: 1500m

  tlsSidecar:
    resources:
      requests:
        cpu: 300m
        memory: 500mi
      limits:
        memory: 2Gi
        cpu: 1500m
