apiVersion: v1
kind: Secret
metadata:
  name: edubois10-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaV1IxWW05cGN6RXdPbWQ0VUVoSGF6UkpSekY2Vm1vd1RVeHZSSGt6UWtwMmNXMDNPRWRhVWxoV1VrWkdUQ3N2ZWpGdFpuTnFSelUyV1ZWaGNTdG5XVGhYVWsxV2FsRXpkbGxZZURkcGNVaFBaVzVMVFdobU5HRnhLM0ZQWjJwQlBUMD0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
