apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: dev
  name: demo-user
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - operations:
          - All
        resource:
          name: stock
          patternType: prefix
          type: topic
      - operations:
          - All
        resource:
          name: stock
          patternType: prefix
          type: group
      - operations:
          - All
        resource:
          type: cluster
      - operations:
          - All
        resource:
          name: stock
          patternType: prefix
          type: transactionalId
    type: simple