kind: Deployment
apiVersion: apps/v1
metadata:
  name: producer-demo
  labels:
    app: producer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-demo
  template:
    metadata:
      labels:
        app: producer-demo
    spec:
      volumes:
        - name: truststore
          secret:
            secretName: demo-truststore
            defaultMode: 420
      containers:
        - name: producer-demo
          image: 'quay.io/edubois10/producer-demo:1.0'
          envFrom:
            - configMapRef:
                name: producer-demo-config-cm
            - secretRef:
                name: producer-demo-config-s
          resources: {}
          volumeMounts:
            - name: truststore
              mountPath: /secrets
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

