apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: playground
  labels:
    strimzi.io/cluster: kafka-playground
spec:
  partitions: 5
  replicas: 2
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824