apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{.Release.Name}}
spec:
  kafkaExporter: 
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    resources:
      limits:
        cpu: '1'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: '3.5'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        tls: true
        type: route
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        tls: true
        type: internal
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    replicas: 3
    storage:
      type: ephemeral
    version: 3.5.0
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 1Gi
    storage:
      type: ephemeral
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
      