apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: demo
spec:
  secretTargetRef:
    - key: username
      name: keda-kafka-secrets
      parameter: username
    - key: password
      name: keda-kafka-secrets
      parameter: password
    - key: sasl
      name: keda-kafka-secrets
      parameter: sasl
    - key: tls
      name: keda-kafka-secrets
      parameter: tls
    - key: ca
      name: keda-kafka-secrets
      parameter: ca
