kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: stock-demo-1
  labels:
    strimzi.io/cluster: dev 
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
