apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: openshift-prometheus
spec:
  name: openshift-prometheus
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: openshift-prometheus
    type: prometheus
    access: proxy
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    isDefault: true
    secureJsonData:
        httpHeaderValue1: Bearer <GRAFANA_SA_TOKEN>
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
      httpHeaderName1: Authorization
    editable: true