kind: Deployment
apiVersion: apps/v1
metadata:
  name: streams-demo
  namespace: helvetia-demo
  labels:
    app: streams-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streams-demo
  template:
    metadata:
      labels:
        app: streams-demo
    spec:
      volumes:
        - name: truststore
          secret:
            secretName: demo-truststore
            defaultMode: 420
        - name: tmp-storage
          emptyDir: {}
      containers:
        - name: streams-demo
          image: 'quay.io/edubois10/kafka-streams-demo:2.0'
          envFrom:
            - configMapRef:
                name: streams-demo-config-cm
            - secretRef:
                name: streams-demo-config-s
          resources: {}
          volumeMounts:
            - name: truststore
              mountPath: /secrets
            - name: tmp-storage
              mountPath: /tmp  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File