apiVersion: v1
kind: LimitRange
metadata:
  name: container-constraints
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 512Mi
    max:
      cpu: 4000m
    min:
      cpu: 100m
    type: Container